/* Generated by ts-generator ver. 0.0.8 */
/* tslint:disable */

/// <reference types="truffle-typings" />

import * as TruffleContracts from ".";

declare global {
  namespace Truffle {
    interface Artifacts {
      require(
        name: "AccountRegistryLogic"
      ): TruffleContracts.AccountRegistryLogicContract;
      require(
        name: "AccreditationRepo"
      ): TruffleContracts.AccreditationRepoContract;
      require(name: "AirdropProxy"): TruffleContracts.AirdropProxyContract;
      require(
        name: "AttestationLogic"
      ): TruffleContracts.AttestationLogicContract;
      require(
        name: "BatchAttestationLogic"
      ): TruffleContracts.BatchAttestationLogicContract;
      require(
        name: "BatchInitializer"
      ): TruffleContracts.BatchInitializerContract;
      require(name: "ERC20"): TruffleContracts.ERC20Contract;
      require(name: "IERC20"): TruffleContracts.IERC20Contract;
      require(name: "Initializable"): TruffleContracts.InitializableContract;
      require(name: "Migrations"): TruffleContracts.MigrationsContract;
      require(name: "MockBLT"): TruffleContracts.MockBLTContract;
      require(name: "Ownable"): TruffleContracts.OwnableContract;
      require(name: "Pausable"): TruffleContracts.PausableContract;
      require(name: "PauserRole"): TruffleContracts.PauserRoleContract;
      require(name: "Poll"): TruffleContracts.PollContract;
      require(name: "SigningLogic"): TruffleContracts.SigningLogicContract;
      require(
        name: "TokenEscrowMarketplace"
      ): TruffleContracts.TokenEscrowMarketplaceContract;
      require(name: "VotingCenter"): TruffleContracts.VotingCenterContract;
    }
  }
}
