version: 2

references:

  # `restore_cache` step necessary for every build step to work
  restore_node_modules: &restore_node_modules
    restore_cache:
      key: node_modules-cache-{{ checksum "package.json" }}

  # Environment that provides the postgres DB `bloom-web-test`
  environment_with_database: &environment_with_database
    - image: circleci/node:8.9.4
      environment:
        PGHOST: 127.0.0.1
        PGUSER: ubuntu
        NODE_ENV: test

jobs:
  install_dependencies:
    docker:
      - image: circleci/node:8.9.4
    steps:
      - checkout

      - run: yarn install --frozen-lockfile --prefer-offline

      # Download and cache dependencies
      - save_cache:
          key: node_modules-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules

  test:
    docker:
      - image: circleci/node:8.9.4
    steps:
      - checkout

      - restore_cache:
          key: dependency-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}

      - run:
          name: Copy truffle config
          command: cp truffle.js.example truffle.js && ls

      - run:
          name: Test suite
          command: bin/test

  verify_typings:
    docker:
      - image: circleci/node:8.9.4
    steps:
      - checkout

      - restore_cache:
          key: dependency-cache-{{ .Branch }}-{{ checksum "yarn.lock" }}

      - run:
          name: Copy truffle config
          command: cp truffle.js.example truffle.js && ls

      - run:
          name: Check that typings are in sync
          command: bin/compile-typings && git diff --exit-code

workflows:
  version: 2
  build_and_test:
    jobs:
      - install_dependencies

      - test:
          requires:
            - install_dependencies

      - verify_typings:
          requires:
            - install_dependencies
